In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path = '../data/disaster_data.csv'
df = pd.read_csv(data_path)
df.head()

   year country disaster_type  deaths  affected    damage
0  2008  Brazil      Wildfire      98      9944   3949087
1  2019   Japan         Flood      48      5320   4436200
2  2014     USA     Hurricane      33      6124   1331559
3  2021  Brazil    Earthquake      55     41036  91403697
4  2004   China    Earthquake     256     38788  13737752

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           1000 non-null   int64
 1   country        1000 non-null   str
 2   disaster_type  1000 non-null   str
 3   deaths         1000 non-null   int64
 4   affected       1000 non-null   int64
 5   damage         1000 non-null   int64
dtypes: int64(4), str(2)
memory usage: 47.0 KB

In [4]:
df.describe()

              year       deaths      affected        damage
count  1000.000000  1000.000000   1000.000000  1.000000e+03
mean   2011.845000   243.849000  13357.583000  1.903461e+07
std       7.095585   272.773789  12684.135033  2.876373e+07
min    2000.000000     0.000000    506.000000  1.933400e+04
25%    2005.000000    46.000000   4490.500000  9.934815e+05
50%    2012.000000   132.000000   8390.000000  3.421174e+06
75%    2018.000000   357.000000  17335.250000  2.768474e+07
max    2024.000000   999.000000  49749.000000  9.949258e+07

In [5]:
df.isnull().sum()

year             0
country          0
disaster_type    0
deaths           0
affected         0
damage           0
dtype: int64

In [6]:
print("Disaster types:", df['disaster_type'].unique())
print("\nDisasters per country:")
print(df['country'].value_counts())

Disaster types: <StringArray>
['Wildfire', 'Flood', 'Hurricane', 'Earthquake', 'Tsunami', 'Drought']
Length: 6, dtype: str

Disasters per country:
country
Japan        162
USA          155
India        149
Mexico       145
Brazil       138
Australia    131
China        120
Name: count, dtype: int64

In [7]:
df.to_csv('../data/processed_disaster_data.csv', index=False)
print("Cleaned CSV saved!")

Cleaned CSV saved!